
sudo: false
language: android

  #before_cache:
  # - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  #- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

  #cache:
  # directories:
  #  - $HOME/.gradle/caches/
# - $HOME/.gradle/wrapper/
env:
  global:
    #- ANDROID_TARGET=android-22
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=x86

android:
  components:
    - tools
    #    - tools
    - platform-tools
    - build-tools-28.0.3
    - echo y
    #- android-28
    - android-26
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
#    - addon
#    - extra
#    - $ANDROID_TARGET
#    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
#    - sys-img-armeabi-v7a-android-23

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-e6a904e8'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - export PATH=/home/vmuser/Android/Sdk/tools/bin$PATH

  #before_install:
  #  - chmod +x ./gradlew
  #  - ./gradlew dependencies || true

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
  #  - echo no | android create avd --force -n test -t android-21 --abi x86
  #  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  #  - emulator -avd test -no-skin -no-audio -no-window &
  - emulator -avd test -no-audio -no-window &
  #  - emulator -avd test -memory 1500 -no-accel -gpu swiftshader -skin 720x1280 -camera-back none -camera-front none -no-boot-anim -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --device 'Nexus 4' --sdcard 128M
  #- emulator -avd test -no-window -skin 768x1280 &
  #  - echo no | android create avd --force -n test -t android-21 --abi x86
  #  - emulator -avd test -memory 1500 -no-accel -gpu swiftshader -skin 720x1280 -camera-back none -camera-front none -no-boot-anim -no-window &
  #  - android-wait-for-emulator
  #  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  #  - adb shell input keyevent 82 &
  #  - ./gradlew connectedAndroidTest --info
  - ./gradlew clean createDebugCoverageReport jacocoTestReport
  #branches:
  # only:
  #  - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
